// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqU_dweSk3I0WeGYTxOyy4marQmErLrrI',
    appId: '1:656760254080:web:54f600f595ebd0e86fc065',
    messagingSenderId: '656760254080',
    projectId: 'project-penyiraman-pencahayaan',
    databaseURL:
        'https://project-penyiraman-pencahayaan-default-rtdb.asia-southeast1.firebasedatabase.app/',
    authDomain: 'project-penyiraman-pencahayaan.firebaseapp.com',
    storageBucket: 'project-penyiraman-pencahayaan.firebasestorage.app',
    measurementId: 'G-FRR9J5WZ1L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhFmfB9JHDZTIKQa7GCSpdgoDaxYS0cFk',
    appId: '1:656760254080:android:2af63561257dfe566fc065',
    messagingSenderId: '656760254080',
    projectId: 'project-penyiraman-pencahayaan',
    databaseURL:
        'https://project-penyiraman-pencahayaan-default-rtdb.asia-southeast1.firebasedatabase.app/',
    storageBucket: 'project-penyiraman-pencahayaan.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCamKp-B5s-t_dVTWc_3YwRF0SAxQNYPrg',
    appId: '1:656760254080:ios:1fadab9ffef8cef86fc065',
    messagingSenderId: '656760254080',
    projectId: 'project-penyiraman-pencahayaan',
    databaseURL:
        'https://project-penyiraman-pencahayaan-default-rtdb.asia-southeast1.firebasedatabase.app/',
    storageBucket: 'project-penyiraman-pencahayaan.firebasestorage.app',
    iosBundleId: 'com.nylo.ios',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCamKp-B5s-t_dVTWc_3YwRF0SAxQNYPrg',
    appId: '1:656760254080:ios:7b2cd9e9ab5a4b4a6fc065',
    messagingSenderId: '656760254080',
    projectId: 'project-penyiraman-pencahayaan',
    databaseURL:
        'https://project-penyiraman-pencahayaan-default-rtdb.asia-southeast1.firebasedatabase.app/',
    storageBucket: 'project-penyiraman-pencahayaan.firebasestorage.app',
    iosBundleId: 'com.nylo.skripsi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqU_dweSk3I0WeGYTxOyy4marQmErLrrI',
    appId: '1:656760254080:web:79632384c74f6abc6fc065',
    messagingSenderId: '656760254080',
    projectId: 'project-penyiraman-pencahayaan',
    databaseURL:
        'https://project-penyiraman-pencahayaan-default-rtdb.asia-southeast1.firebasedatabase.app/',
    authDomain: 'project-penyiraman-pencahayaan.firebaseapp.com',
    storageBucket: 'project-penyiraman-pencahayaan.firebasestorage.app',
    measurementId: 'G-2GYK0GKKW4',
  );
}
